#!/usr/bin/env python3
"""
Download NOAA chart data for the Chart tab: NCDS pre-rendered base tiles plus
ENC vector features for click-to-inspect (soundings, buoys, beacons, lights,
bridges, hazards).

The base chart is NOAA's own Chart Display Service (NCDS) -- pre-rendered
raster tiles with real paper-chart symbology, distributed as a single
MBTiles (SQLite) file per region, generated by NOAA directly from their ENC
data. dashboard_api.py serves tiles straight out of that file by querying the
SQLite db per request, so there's no server-side rendering step for it here
at all -- just a download.

Raster tiles have no clickable features baked in, though, so the vector
layers (S-57 object classes converted to GeoJSON via ogr2ogr) still get
downloaded and processed separately, same as ENC always requires -- that's
what "click a buoy for details" actually needs.

Requires gdal-bin (ogr2ogr):
    sudo apt install -y gdal-bin

Usage:
    python3 chart_tools.py download-ncds <region>       # e.g. ncds_10
    python3 chart_tools.py sync US5TPAEF US5TPAFG ...    # ENC vector cells
    python3 chart_tools.py download US5TPAEF
    python3 chart_tools.py process US5TPAEF
    python3 chart_tools.py sync-manifest chart_data/enc_manifest.json   # bulk sync every
        # cell in a manifest ({band: [cellnames]}) -- built for hours-long runs, safe to
        # re-run (skips cells already processed), one bad cell doesn't abort the rest.

To find the NCDS region covering a location, query its metadata service:
    https://gis.charttools.noaa.gov/arcgis/rest/services/MarineChart_Services/ncds_tilecache_metadata/MapServer/0/query?geometry=<lon>,<lat>&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=name,baseline&returnGeometry=false&f=json
(This endpoint is intermittently flaky -- NOAA's ArcGIS-hosted GIS services
generally are -- retry a few times if it 500s.)

To find the ENC cell(s) covering a location, query NOAA's grid footprint
service (layer 1=harbor, 2=approach, 3=coastal, 4=general scale):
    https://encdirect.noaa.gov/arcgis/rest/services/MarineChart_Services/Gridded_NOAA_ENC/MapServer/1/query?geometry=<lon>,<lat>&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=CELLNAME,SCALE&returnGeometry=false&f=json
"""
import sys
import os
import zipfile
import subprocess
import shutil
import json
import glob
import urllib.request

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(BASE_DIR, 'chart_data', 'raw')
PROCESSED_DIR = os.path.join(BASE_DIR, 'chart_data', 'processed')
NCDS_DIR = os.path.join(BASE_DIR, 'chart_data', 'ncds')

# S-57 object classes the frontend renders as clickable vector features.
# Ground (water/land/depth shading) comes from NOAA's own NCDS raster now,
# so unlike an ENC-only setup there's no need to export DEPARE/LNDARE/etc.
# here at all -- this list is just what needs to be clickable.
LAYERS = [
    'SOUNDG',  # individual soundings (point, depth from Z via ADD_SOUNDG_DEPTH)
    'BOYLAT', 'BOYCAR', 'BOYSAW', 'BOYSPP', 'BOYISD',  # buoys by IALA category
    'BCNLAT', 'BCNCAR', 'BCNSAW', 'BCNSPP', 'BCNISD',  # beacons by IALA category
    'LIGHTS',  # lights (on any structure)
    'BRIDGE',  # bridges
    'WRECKS', 'OBSTRN',  # hazards
    'FAIRWY', 'RESARE', 'CTNARE',  # fairways, restricted/caution areas
]

OGR_OPEN_OPTIONS = [
    '-oo', 'SPLIT_MULTIPOINT=ON',
    '-oo', 'ADD_SOUNDG_DEPTH=ON',
    '-oo', 'RETURN_PRIMITIVES=OFF',
    '-oo', 'RETURN_LINKAGES=OFF',
    '-oo', 'UPDATES=APPLY',
]


def download_ncds(region):
    """Download a single NCDS pre-rendered MBTiles region (large -- several
    hundred MB). dashboard_api.py queries it directly; nothing to convert."""
    url = f'https://distribution.charts.noaa.gov/ncds/mbtiles/{region}.mbtiles'
    os.makedirs(NCDS_DIR, exist_ok=True)
    dest = os.path.join(NCDS_DIR, f'{region}.mbtiles')
    # Download to a temp name and rename into place only once complete --
    # the live dashboard reads straight out of chart_data/ncds/*.mbtiles, and
    # without this a request landing mid-download would try to open a
    # partial file and get a genuine "database disk image is malformed"
    # error, not a clean 404.
    tmp_dest = dest + '.part'
    print(f'Downloading {url} (this is a large file, may take a while) ...')
    urllib.request.urlretrieve(url, tmp_dest)
    os.rename(tmp_dest, dest)
    print(f'  -> {dest} ({os.path.getsize(dest) / 1e6:.1f} MB)')
    return dest


def download(cell):
    url = f'https://charts.noaa.gov/ENCs/{cell}.zip'
    dest_dir = os.path.join(RAW_DIR, cell)
    os.makedirs(dest_dir, exist_ok=True)
    zip_path = os.path.join(dest_dir, f'{cell}.zip')
    print(f'Downloading {url} ...')
    urllib.request.urlretrieve(url, zip_path)
    with zipfile.ZipFile(zip_path) as z:
        z.extractall(dest_dir)
    print(f'  -> {dest_dir}')
    return dest_dir


def _find_base_file(dest_dir, cell):
    matches = glob.glob(os.path.join(dest_dir, '**', f'{cell}.000'), recursive=True)
    if not matches:
        raise FileNotFoundError(f'No {cell}.000 found under {dest_dir} -- run download first')
    return matches[0]


def _collect_coords(geom, lons, lats):
    t, coords = geom['type'], geom['coordinates']
    if t == 'Point':
        lons.append(coords[0]); lats.append(coords[1])
    elif t in ('MultiPoint', 'LineString'):
        for c in coords:
            lons.append(c[0]); lats.append(c[1])
    elif t in ('MultiLineString', 'Polygon'):
        for ring in coords:
            for c in ring:
                lons.append(c[0]); lats.append(c[1])
    elif t == 'MultiPolygon':
        for poly in coords:
            for ring in poly:
                for c in ring:
                    lons.append(c[0]); lats.append(c[1])


def _compute_bounds(out_dir):
    lats, lons = [], []
    for path in glob.glob(os.path.join(out_dir, '*.geojson')):
        with open(path) as f:
            data = json.load(f)
        for feat in data['features']:
            _collect_coords(feat['geometry'], lons, lats)
    if not lats:
        return None
    return {'south': min(lats), 'north': max(lats), 'west': min(lons), 'east': max(lons)}


def process(cell):
    dest_dir = os.path.join(RAW_DIR, cell)
    base_file = _find_base_file(dest_dir, cell)
    out_dir = os.path.join(PROCESSED_DIR, cell)
    os.makedirs(out_dir, exist_ok=True)

    written = []
    for layer in LAYERS:
        out_path = os.path.join(out_dir, f'{layer}.geojson')
        result = subprocess.run(
            ['ogr2ogr', '-f', 'GeoJSON', '-t_srs', 'EPSG:4326', *OGR_OPEN_OPTIONS,
             out_path, base_file, layer],
            capture_output=True, text=True,
        )
        # A cell not carrying a given object class (e.g. no WRECKS here) makes
        # ogr2ogr fail to find the layer -- that's a normal "not present",
        # not an error worth surfacing.
        if result.returncode != 0:
            if os.path.exists(out_path):
                os.remove(out_path)
            continue
        with open(out_path) as f:
            data = json.load(f)
        if not data.get('features'):
            os.remove(out_path)
            continue
        written.append((layer, len(data['features'])))

    meta = {'cell': cell, 'layers': dict(written), 'bounds': _compute_bounds(out_dir)}
    with open(os.path.join(out_dir, 'meta.json'), 'w') as f:
        json.dump(meta, f, indent=2)

    print(f'{cell}: {len(written)} layers written -> {out_dir}')
    for layer, count in written:
        print(f'   {layer}: {count} features')
    return meta


def sync(cell):
    download(cell)
    return process(cell)


def sync_manifest(manifest_path):
    """Bulk sync every cell listed in a manifest JSON ({band: [cellnames]},
    e.g. from querying encdirect.noaa.gov's Gridded_NOAA_ENC footprint
    service). Built for a run measured in hours, not the handful-of-cells
    case sync() covers directly: skips cells already processed (safe to
    re-run after an interruption), and a single cell failing (a bad
    download, a corrupt zip, whatever) is logged and skipped rather than
    aborting everything else behind it."""
    with open(manifest_path) as f:
        manifest = json.load(f)
    all_cells = sorted({cell for cells in manifest.values() for cell in cells})
    total = len(all_cells)
    ok = skipped = 0
    failed = []
    for i, cell in enumerate(all_cells, 1):
        if os.path.exists(os.path.join(PROCESSED_DIR, cell, 'meta.json')):
            skipped += 1
            continue
        try:
            sync(cell)
            ok += 1
        except Exception as e:
            print(f'  FAILED {cell}: {e}')
            failed.append(cell)
        if i % 25 == 0 or i == total:
            print(f'--- progress: {i}/{total} cells ({ok} synced, {skipped} already done, {len(failed)} failed) ---')
    print(f'Done: {ok} synced, {skipped} already done, {len(failed)} failed out of {total}')
    if failed:
        failed_path = os.path.join(BASE_DIR, 'chart_data', 'failed_cells.json')
        with open(failed_path, 'w') as f:
            json.dump(failed, f, indent=2)
        print(f'Failed cell list -> {failed_path}')


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    cmd, args = sys.argv[1], sys.argv[2:]
    if cmd in ('process', 'sync', 'sync-manifest') and shutil.which('ogr2ogr') is None:
        print('ogr2ogr not found -- install it first: sudo apt install -y gdal-bin')
        sys.exit(1)
    for arg in args:
        if cmd == 'download':
            download(arg)
        elif cmd == 'process':
            process(arg)
        elif cmd == 'sync':
            sync(arg)
        elif cmd == 'sync-manifest':
            sync_manifest(arg)
        elif cmd == 'download-ncds':
            download_ncds(arg)
        else:
            print(f'Unknown command: {cmd}')
            sys.exit(1)
